# Generated by Django 4.2.1 on 2023-05-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Post',
        ),
    ]
